version: "3.1"
services:
  nodejs:
    ports:
      - 8000:8000
    build:
      context: ./docker_images/
      dockerfile: node_image
    image: assignment
    volumes:
      - ./.npm:/root/.npm/
      - ./:/code
    depends_on:
      - mongo
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_PORT: 27017
      MONGO_HOST: mongo
      MONGO_DB_NAME: assignment
      RANDOM_STRING: this is the random string required in the header
    command: npm run start
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./volumes/mongoData:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
